name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@98.84.178.229 -t "
          cd ci_cd_first/ && 
          git pull origin main &&
          export PATH=$HOME/.nvm/versions/node/v22.13.1/bin:$PATH &&
          sudo npm install -g pnpm pm2 &&  # Install both pnpm and pm2
          pnpm install &&
          pnpm run build &&
          pm2 restart fe-server &&
          pm2 restart http-server &&
          pm2 restart ws-server"
   